import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-primary",
    "bg-primary-hover",
    "bg-primary-soft",
    "text-primary",
    "text-text",
    "text-text-2",
    "text-text-3",
    "text-success",
    "text-warning",
    "text-error",
    "text-info",
    "bg-success-soft",
    "bg-warning-soft",
    "bg-error-soft",
    "bg-info-soft",
    "bg-surface",
    "bg-surface-2",
    "bg-bg",
    "border-border",
    "border-primary",
    "hover:bg-primary-hover",
    "hover:bg-primary-soft",
    "hover:bg-surface-2",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-soft": "var(--primary-soft)",
        "primary-text": "var(--primary-text)",
        info: "var(--info)",
        "info-soft": "var(--info-soft)",
        success: "var(--success)",
        "success-soft": "var(--success-soft)",
        warning: "var(--warning)",
        "warning-soft": "var(--warning-soft)",
        error: "var(--error)",
        "error-soft": "var(--error-soft)",
        bg: "var(--bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        text: "var(--text)",
        "text-2": "var(--text-2)",
        "text-3": "var(--text-3)",
      },
      borderRadius: {
        DEFAULT: "var(--r)",
        sm: "var(--r-sm)",
        lg: "var(--r-lg)",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
